# Generated by Django 5.2.4 on 2026-04-26

from django.db import migrations, models


def clear_closed_at_for_active_listings(apps, schema_editor):
    AuctionListing = apps.get_model("auctions", "AuctionListing")
    AuctionListing.objects.filter(is_active=True).update(closed_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_auctionlisting_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            clear_closed_at_for_active_listings,
            migrations.RunPython.noop,
        ),
    ]
