# Generated by Django 5.2.4 on 2025-08-14 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_is_active_auctionlisting_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auctionlisting'),
        ),
    ]
